### ISSUE TITLE
-y option to complement -i

### ISSUE THREAD

**Issue by mehulkar** [prysk/prysk#197]
I'd like to run  interactive mode with `-i` and accept all changes. Since my test suite is slow, it would be useful to just walk away and come back with everything update and then pick and choose what to accept with `git add -p` or whatever.

**Comment by LMG** [comment]
Like this: https://github.com/prysk/prysk/blob/4c12bd636dab29b3b12a687a755b70f61296da6a/prysk/cli.py#L145 ?

**Comment by mehulkar** [comment]
Yes, exactly! My mistake I missed that in the docs 😨
