### ISSUE TITLE
📝 Access Denied during cleanup on Github Actions windows-runner

### ISSUE THREAD

**Issue by mehulkar** [prysk/prysk#206]
During cleanup, I see a failure to `os.unlink` that I can't control. Filing this issue in case there are any obvious answers. The specific file that is failing to be removed is in the `.git` directory that is being initialized during my test, but it seems weird that it works on ubuntu/macOS runners, but not on Windows. It's possible the location of the tmp directory needs to be customized.

```
  # Ran 1 tests, 0 skipped, 1 failed.
  Traceback (most recent call last):
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "D:\a\turbo\turbo\turborepo-tests\integration\.cram_env\Scripts\prysk.exe\__main__.py", line 7, in <module>
    File "D:\a\turbo\turbo\turborepo-tests\integration\.cram_env\lib\site-packages\prysk\__init__.py", line 9, in main
      sys.exit(prysk.cli.main())
    File "D:\a\turbo\turbo\turborepo-tests\integration\.cram_env\lib\site-packages\prysk\cli.py", line 46, in main
      return _Cli().main(argv)
    File "D:\a\turbo\turbo\turborepo-tests\integration\.cram_env\lib\site-packages\prysk\cli.py", line 526, in main
      shutil.rmtree(tmpdir)
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\shutil.py", line 759, in rmtree
      return _rmtree_unsafe(path, onerror)
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\shutil.py", line 624, in _rmtree_unsafe
      _rmtree_unsafe(fullname, onerror)
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\shutil.py", line 624, in _rmtree_unsafe
      _rmtree_unsafe(fullname, onerror)
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\shutil.py", line 624, in _rmtree_unsafe
      _rmtree_unsafe(fullname, onerror)
    [Previous line repeated 1 more time]
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\shutil.py", line 629, in _rmtree_unsafe
      onerror(os.unlink, fullname, sys.exc_info())
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\shutil.py", line 627, in _rmtree_unsafe
      os.unlink(fullname)
  PermissionError: [WinError 5] Access is denied: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\prysk-tests-alug5f3h\\monorepo.t\\.git\\objects\\14\\4dc55f8fb8924d47fa4818ae9eb459d8dce435'
   ELIFECYCLE  Test failed. See above for more details.
```

**Comment by nigels-com** [comment]
On windows this could be due to a read handle for that particular file.
Explicitly closing files may help, depending on where those might be waiting for garbage collection?

**Comment by mehulkar** [comment]
I looked around and this seems like it's a known thing with `.git` directories. Here's one workaround: https://github.com/nrosenstein-stuff/flux-ci/commit/04116223346c57738a06fe9ea267874468538b37

> Explicitly closing files may help, depending on where those might be waiting for garbage collection?

Any idea how I would do this in Windows for git?

**Comment by mehulkar** [comment]
What's interesting is that I'm unable to reproduce this with a normal bash script. See [`run.py`](https://github.com/mehulkar/prysk-on-windows/blob/953a69ac87aa5deb3512114977fc17ad64bc0c5e/run.py) vs [`run.sh`](https://github.com/mehulkar/prysk-on-windows/blob/953a69ac87aa5deb3512114977fc17ad64bc0c5e/run.sh) in my simple repo. The [Github action run](https://github.com/mehulkar/prysk-on-windows/actions/runs/6741542275) shows the difference also

**Comment by nigels-com** [comment]
Oh, if there is no other process holding a handle to that particular file...  it's just a permissions problem then?

**Comment by nigels-com** [comment]
Well, that's not fun at all.
https://stackoverflow.com/questions/2656322/shutil-rmtree-fails-on-windows-with-access-is-denied

```
def onerror(func, path, exc_info):
    """
    Error handler for ``shutil.rmtree``.

    If the error is due to an access error (read only file)
    it attempts to add write permission and then retries.

    If the error is for another reason it re-raises the error.
    
    Usage : ``shutil.rmtree(path, onerror=onerror)``
    """
    import stat
    # Is the error an access error?
    if not os.access(path, os.W_OK):
        os.chmod(path, stat.S_IWUSR)
        func(path)
    else:
        raise
       ```

**Comment by mehulkar** [comment]
@nigels-com I opened #207 with something similar

**Comment by Nicoretti** [comment]
Hi @nigels-com and @mehulkar,

I wanted to quickly mention that I'm currently quite short on time. I've invited @mehulkar to the organization as a member because he's been a frequent contributor. Since both of you are using Windows while I am not, I'm confident that you can work together to find a reasonable solution to the problem. If you encounter any permission issues or need feedback, please don't hesitate to reach out to me.

best
Nico

**Comment by mehulkar** [comment]
Thanks @Nicoretti for the invite! I don't think I have merge permissions, but will continue the conversation in #207.

**Comment by Nicoretti** [comment]
@mehulkar looks like an extra invite and settings in the repo itself was required. You should be able to merge now.
