### ISSUE TITLE
interactive.t: Fails with mksh

### ISSUE THREAD

**Issue by lanodan** [prysk/prysk#230]
### Checklist
In order to improve the time, how long a bugfix does take, please make sure you address as much as possible of the following checklist.

- [x] I have reproduced the issue with at least the latest released version of prysk.
- [x] I have added references to issues that sound similar.

## Reproducing the Issue

1. Install [mksh](http://mirbsd.de/mksh) (your distro likely has it)
2. `python -m prysk --shell=mksh test/integration`

## Expected Behaviour

Tests pass, like with other shells (I also tested `dash` and `bash`, they work fine)

## Actual Behaviour
```
...!
--- test/integration/prysk/interactive.t
+++ test/integration/prysk/interactive.t.err
@@ -243,38 +243,40 @@
   !
   --- examples/fail.t
   +++ examples/fail.t.err
-  @@ -1,18 +1,18 @@
-   Output needing escaping:
-
-     $ printf '\00\01\02\03\04\05\06\07\010\011\013\014\016\017\020\021\022\n'
-  -  foo
-  +  \x00\x01\x02\x03\x04\x05\x06\x07\x08\t\x0b\x0c\x0e\x0f\x10\x11\x12 (esc)
-     $ printf '\023\024\025\026\027\030\031\032\033\034\035\036\037\040\047\n'
-  -  bar
-  +  \x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f ' (esc)
-
-   Wrong output and bad regexes:
-
-     $ echo 1
-  -  2
-  +  1
-     $ printf '1\nfoo\n1\n'
-  -  +++ (re)
-  -  foo\ (re)
-  -   (re)
-  +  1
-  +  foo
-  +  1
-
-   Filler to force a second diff hunk:
-
-  @@ -20,5 +20,6 @@
-   Offset regular expression:
-
-     $ printf 'foo\n\n1\n'
-  +  foo
-
-     \d (re)
+  @@ -1,18 +1,19 @@
+   Output needing escaping:
+
+     $ printf '\00\01\02\03\04\05\06\07\010\011\013\014\016\017\020\021\022\n'
+  -  foo
+  +  /bin/mksh: <stdin>[2]: printf: inaccessible or not found
+  +  [127]
+     $ printf '\023\024\025\026\027\030\031\032\033\034\035\036\037\040\047\n'
+  -  bar
+  +  /bin/mksh: <stdin>[4]: printf: inaccessible or not found
+  +  [127]
+
+   Wrong output and bad regexes:
+
+     $ echo 1
+  -  2
+  +  1
+     $ printf '1\nfoo\n1\n'
+  -  +++ (re)
+  -  foo\ (re)
+  -   (re)
+  +  /bin/mksh: <stdin>[8]: printf: inaccessible or not found
+  +  [127]
+
+   Filler to force a second diff hunk:
+
+  @@ -20,5 +21,5 @@
+   Offset regular expression:
+
+     $ printf 'foo\n\n1\n'
+  -
+  -  \d (re)
+  +  /bin/mksh: <stdin>[10]: printf: inaccessible or not found
+  +  [127]
   Accept this change?  y
   patch failed
   examples/fail.t: merge failed
@@ -283,5 +285,5 @@
   [1]
   $ md5 examples/fail.t examples/fail.t.err
   .*\b0f598c2b7b8ca5bcb8880e492ff6b452\b.* (re)
-  .*\b7a23dfa85773c77648f619ad0f9df554\b.* (re)
+  ddd312cbbde839ce1828dc0ec875426c
   $ rm patch examples/fail.t.err
.....
# Ran 9 tests, 0 skipped, 1 failed.
```

### System
- Gentoo Linux
- Python 3.11.7
- mksh 59c
- prysk 0.17.0 (github autogenerated tarball)

**Comment by liskin** [comment]
https://stackoverflow.com/a/26986720 recommends using `busybox printf` so we could conditionally add an alias to https://github.com/prysk/prysk/blob/master/test/integration/prysk/setup.sh for mksh.

**Comment by lanodan** [comment]
This StackOverflow answer is wrong, at least outside of Android, the builtin printf is discouraged and opt-in.

Also since R51 system printf is preferred anyway: http://www.mirbsd.org/mksh-faq.htm#printf-c

```
$ command -v printf
/usr/bin/printf
$ qfile -v /usr/bin/printf
sys-apps/coreutils-9.4: /usr/bin/printf
```

**Comment by liskin** [comment]
> This StackOverflow answer is wrong, at least outside of Android, the builtin printf is discouraged and opt-in.

Yes, that is indeed what the answer literally says—that the builtin printf is opt-in and not recommended. You might want to reread it. 😏

> Also since R51 system printf is preferred anyway […]

Well then why are you getting `/bin/mksh: <stdin>[10]: printf: inaccessible or not found` if you have a printf in your system? 🤔

**Comment by lanodan** [comment]
[2024-01-30 05:03:09-0800] Tomáš Janoušek:
>> This StackOverflow answer is wrong, at least outside of Android, the builtin printf is discouraged and opt-in.
>
>Yes, that is indeed what the answer literally says—that the builtin printf is opt-in and not recommended. You might want to reread it. 😏

It is at least horribly misleading when taken out of the context of this massive bug in Android.  
In fact you got trapped in it with replying about doing an alias with "busybox printf", while any reasonable system would have a printf executable (POSIX standard), even if only busybox would be installed.

>> Also since R51 system printf is preferred anyway […]
>
>Well then why are you getting `/bin/mksh: <stdin>[10]: printf: inaccessible or not found` if you have a printf in your system? 🤔

I don't know. I don't think it's on mksh as printf works fine both interactively and in scripts, but at the same time I'd except even a forcibily used builtin printf (as dash and bash have one) to lead to a different error, such as:
```
$ builtin printf
sh: builtin: printf: not found
```

To add to the weirdness, running `examples/fail.t` directly works as expected:
```
$ python -m prysk --shell=mksh -n -i examples/fail.t
!
--- examples/fail.t
+++ examples/fail.t.err
@@ -1,18 +1,18 @@
  Output needing escaping:

    $ printf '\00\01\02\03\04\05\06\07\010\011\013\014\016\017\020\021\022\n'
-  foo
+  \x00\x01\x02\x03\x04\x05\x06\x07\x08\t\x0b\x0c\x0e\x0f\x10\x11\x12 (esc)
    $ printf '\023\024\025\026\027\030\031\032\033\034\035\036\037\040\047\n'
-  bar
+  \x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f ' (esc)

  Wrong output and bad regexes:

    $ echo 1
-  2
+  1
    $ printf '1\nfoo\n1\n'
-  +++ (re)
-  foo\ (re)
-   (re)
+  1
+  foo
+  1

  Filler to force a second diff hunk:

@@ -20,5 +20,6 @@
  Offset regular expression:

    $ printf 'foo\n\n1\n'
+  foo

    \d (re)
Accept this change? [yN] n

# Ran 1 tests, 0 skipped, 1 failed.
```

**Comment by liskin** [comment]
Right, I see, indeed I got trapped into chasing a red herring.

The real issue is probably this: https://github.com/prysk/prysk/blob/f6124c325a39eae2812d52f6e42be436d5213ee3/test/integration/prysk/interactive.t#L233-L242

Setting `PATH=.` results in any non-builtins being unavailable. Perhaps `PATH=.:$PATH` would fix this?

**Comment by Nicoretti** [comment]
Thanks @lanodan and @liskin for figuring this one out in the meantime.
I plan to merge the changes and create a release this weekend.
