### ISSUE TITLE
✨ (Optionally) disable escaping for printable UTF-8 characters

### ISSUE THREAD

**Issue by liskin** [prysk/prysk#232]
# Summary
prysk currently escapes any lines that aren't printable ASCII. I'd love to have an option to leave valid printable UTF-8 unescaped.

# Details

## Background & Context
As I mentioned in https://github.com/prysk/prysk/issues/224, I've been using cram for years to make sure the examples in my README.md files are up to date. Some of those READMEs, however, contain example output with printable Unicode characters that aren't in 7-bit ASCII. I need those examples to be human-readable, and prysk's escaping messes that up.

## Examples

An example of this is here: https://github.com/liskin/arbtt-chart/blob/7fd576e158dd616a40de25fe9ff6cb0125899ea4/README.md#custom-inputs

So far, I've been monkey patching cram/prysk to disable escaping completely:
https://github.com/liskin/cookiecutter-python-cli/blob/ac88c73b006b686802b3c314b9a79b090929a4f1/%7B%7Bcookiecutter._dest_dir%7D%7D/tests/prysk-noescape.py#L7
https://github.com/liskin/cookiecutter-python-cli/blob/f120b1c23cb6eb5fc350109272c4b809220699f2/%7B%7Bcookiecutter._dest_dir%7D%7D/tests/cram-noescape.py#L7
This, however, requires version-pinning the prysk dependency to make sure this doesn't break, and thus incurrs additional maintenance costs.

## References
* draft implementation: https://github.com/liskin/prysk/commit/da7878767ae0fb9a592c77fbe225fbe8d9b291d1

# Task(s)
- [ ] decide whether this should be optional or whether to change behaviour unconditionally
- [ ] implement whatever's decided (https://github.com/liskin/prysk/commit/da7878767ae0fb9a592c77fbe225fbe8d9b291d1 might be a good start)

**Comment by Nicoretti** [comment]
Hi @liskin,

Sorry for being a bit late. I really like your idea. Whether it should be optional or default behavior, I'm not sure though. I have no idea how many people we will break if we make the new behavior the default. Still, I feel like your suggested version is the nicer default in a lot of cases. So, I would be willing to make it the default and have the old behavior as optional if we indicate the potential breaking changes in the changelog with a how-to fix (e.g., by adding a .pryskrc with the appropriate setting).

Last but not least, are you up for implementing the feature?

best
Nico

**Comment by liskin** [comment]
> Last but not least, are you up for implementing the feature?

Sure, that was my intention from the start. I've been dealing with some personal issues lately so went silent for a bit (was avoiding computers tbh) but it's still in my TODO and I'm somewhat optimistic I'll get to it in the near future.

**Comment by Nicoretti** [comment]
Hi @liskin, 

Thanks for the update 👍 .
No worries, take care of you and your life, thats way more important! (Wish you all the best 🤞 )
We will keep the bit's waiting for you 😉.

best
Nico
